#!/usr/bin/env ruby
git_bundles = %w{
  https://github.com/junegunn/fzf
  https://github.com/nixprime/cpsm.git
  https://github.com/janko-m/vim-test
  https://github.com/mxw/vim-jsx.git
  https://github.com/scrooloose/syntastic.git
  https://github.com/bling/vim-airline
  https://github.com/terryma/vim-multiple-cursors
  https://github.com/jgdavey/tslime.vim
  https://github.com/thoughtbot/vim-rspec
  https://github.com/tomtom/tlib_vim.git
  https://github.com/MarcWeber/vim-addon-mw-utils.git
  https://github.com/matthewsimo/angular-vim-snippets
  https://github.com/tpope/vim-rake
  https://github.com/altercation/vim-colors-solarized.git
  https://github.com/tpope/vim-dispatch
  https://github.com/ervandew/supertab.git
  https://github.com/ecomba/vim-ruby-refactoring.git
  https://github.com/jgdavey/vim-blockle.git
  https://github.com/kchmck/vim-coffee-script.git
  https://github.com/scrooloose/nerdtree.git
  https://github.com/sickill/vim-pasta.git
  https://github.com/tomtom/tcomment_vim.git
  https://github.com/tpope/vim-cucumber.git
  https://github.com/tpope/vim-fugitive.git
  https://github.com/tpope/vim-git.git
  https://github.com/tpope/vim-haml.git
  https://github.com/mihaifm/bufstop
  https://github.com/tpope/vim-markdown.git
  https://github.com/tpope/vim-surround.git
  https://github.com/tpope/vim-vividchalk.git
  https://github.com/tpope/vim-rails.git
  https://github.com/vim-scripts/jQuery.git
  https://github.com/tsaleh/vim-align
  https://github.com/vim-scripts/Rename
}

# https://github.com/ctrlpvim/ctrlp.vim.git
require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

threads = []
git_bundles.each do |url|
  puts url
  threads << Thread.new do
    `git clone -q #{url}`
  end
end
threads.each(&:join)

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }
