#!/usr/bin/env ruby
git_bundles = %w{
  https://github.com/Shougo/neocomplcache.git
  https://github.com/ecomba/vim-ruby-refactoring.git
  https://github.com/jgdavey/vim-blockle.git
  https://github.com/kchmck/vim-coffee-script.git
  https://github.com/kien/ctrlp.vim.git
  https://github.com/pangloss/vim-javascript.git
  https://github.com/scrooloose/nerdtree.git
  https://github.com/sickill/vim-pasta.git
  https://github.com/tomtom/tcomment_vim.git
  https://github.com/tpope/vim-cucumber.git
  https://github.com/tpope/vim-endwise.git
  https://github.com/tpope/vim-fugitive.git
  https://github.com/tpope/vim-git.git
  https://github.com/tpope/vim-haml.git
  https://github.com/tpope/vim-markdown.git
  https://github.com/tpope/vim-rails.git
  https://github.com/tpope/vim-surround.git
  https://github.com/tpope/vim-vividchalk.git
  https://github.com/vim-ruby/vim-ruby.git
  https://github.com/vim-scripts/jQuery.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }


